language: java
dist: trusty
sudo: false
cache:
  directories:
  - $HOME/.gradle
  - ./Flank/.gradle
  - ./cloud_testing/apis/testing/.gradle
  - ./cloud_testing/kotlin_poc/.gradle
script:
- ./gradle/gradlew -p Flank clean build
- ./gradle/gradlew -p cloud_testing/kotlin_poc clean build
